DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    --id INT PRIMARY KEY AUTO_INCREMENT,
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(500),
    created_at TIMESTAMP DEFAULT NOW()
);

